class MCDSS:

    def __init__(self):

        self.database = {

            "mobile": [
                {"name": "Samsung M14", "price": 12000, "performance": 8, "battery": 9, "quality": 8, "brand": 8},
                {"name": "Redmi Note 13", "price": 15000, "performance": 9, "battery": 8, "quality": 8, "brand": 7},
                {"name": "Realme Narzo 70", "price": 14000, "performance": 8, "battery": 8, "quality": 9, "brand": 7},
                {"name": "Moto G85", "price": 18000, "performance": 9, "battery": 8, "quality": 8, "brand": 8},
                {"name": "Poco X6", "price": 20000, "performance": 10, "battery": 8, "quality": 8, "brand": 7}
            ],

            "laptop": [
                {"name": "Dell Inspiron", "price": 55000, "performance": 9, "battery": 8, "quality": 8, "brand": 9},
                {"name": "HP Pavilion", "price": 60000, "performance": 8, "battery": 8, "quality": 9, "brand": 8},
                {"name": "Lenovo IdeaPad", "price": 50000, "performance": 8, "battery": 9, "quality": 8, "brand": 8},
                {"name": "ASUS Vivobook", "price": 65000, "performance": 9, "battery": 8, "quality": 8, "brand": 8},
                {"name": "Acer Aspire", "price": 52000, "performance": 8, "battery": 8, "quality": 8, "brand": 7}
            ],

            "car": [
                {"name": "Tata Nexon", "price": 950000, "performance": 9, "battery": 0, "quality": 10, "brand": 9},
                {"name": "Hyundai Venue", "price": 1000000, "performance": 8, "battery": 0, "quality": 9, "brand": 8},
                {"name": "Maruti Brezza", "price": 900000, "performance": 8, "battery": 0, "quality": 8, "brand": 9},
                {"name": "Kia Sonet", "price": 1100000, "performance": 9, "battery": 0, "quality": 9, "brand": 8},
                {"name": "Mahindra XUV300", "price": 1050000, "performance": 9, "battery": 0, "quality": 9, "brand": 9}
            ],

            "bike": [
                {"name": "TVS Raider", "price": 100000, "performance": 8, "battery": 0, "quality": 8, "brand": 8},
                {"name": "Honda Shine", "price": 90000, "performance": 8, "battery": 0, "quality": 9, "brand": 9},
                {"name": "Bajaj Pulsar", "price": 120000, "performance": 9, "battery": 0, "quality": 8, "brand": 8},
                {"name": "Yamaha FZ", "price": 130000, "performance": 9, "battery": 0, "quality": 9, "brand": 8},
                {"name": "Hero Xtreme", "price": 115000, "performance": 8, "battery": 0, "quality": 8, "brand": 8}
            ],

            "college": [
                {"name": "ABC University", "price": 150000, "performance": 9, "battery": 0, "quality": 8, "brand": 9},
                {"name": "XYZ University", "price": 180000, "performance": 8, "battery": 0, "quality": 9, "brand": 9},
                {"name": "PQR Institute", "price": 120000, "performance": 8, "battery": 0, "quality": 8, "brand": 8},
                {"name": "Tech University", "price": 200000, "performance": 10, "battery": 0, "quality": 9, "brand": 9},
                {"name": "National College", "price": 170000, "performance": 9, "battery": 0, "quality": 8, "brand": 8}
            ],

            "house": [
                {"name": "Apartment A", "price": 3500000, "performance": 8, "battery": 0, "quality": 9, "brand": 8},
                {"name": "Apartment B", "price": 4500000, "performance": 9, "battery": 0, "quality": 8, "brand": 9},
                {"name": "Villa C", "price": 5000000, "performance": 10, "battery": 0, "quality": 10, "brand": 9},
                {"name": "Flat D", "price": 3000000, "performance": 7, "battery": 0, "quality": 8, "brand": 7},
                {"name": "Gated House E", "price": 4000000, "performance": 9, "battery": 0, "quality": 9, "brand": 8}
            ]
        }

    def recommend(self):

        print("=" * 50)
        print("SMART MULTI-CRITERIA DECISION SUPPORT SYSTEM")
        print("=" * 50)

        print("\nAvailable Domains:")
        print("Mobile")
        print("Laptop")
        print("Car")
        print("Bike")
        print("College")
        print("House")

        domain = input("\nEnter Item Name: ").lower()

        if domain not in self.database:
            print("Invalid Category!")
            return

        budget = float(input("Enter Your Budget: "))

        minimum_budget = min(item["price"] for item in self.database[domain])

        if budget < minimum_budget:
            print("\nINVALID BUDGET!")
            print(f"Minimum budget required is Rs.{minimum_budget}")
            return

        available = []

        for item in self.database[domain]:
            if item["price"] <= budget:
                available.append(item)

        if len(available) == 0:
            print("No options available.")
            return

        print("\nOptions Generated By System:")

        for i, item in enumerate(available, start=1):
            print(f"{i}. {item['name']}")

        print("\nEnter Preference Importance (1-10)")

        performance_weight = int(input("Performance Importance: "))
        quality_weight = int(input("Quality Importance: "))
        brand_weight = int(input("Brand Importance: "))
        price_weight = int(input("Price Importance: "))

        results = []

        for item in available:

            price_score = (
                (budget - item["price"]) / budget
            ) * 10

            total_score = (
                item["performance"] * performance_weight +
                item["quality"] * quality_weight +
                item["brand"] * brand_weight +
                price_score * price_weight
            )

            results.append({
                "name": item["name"],
                "price": item["price"],
                "score": total_score
            })

        results.sort(
            key=lambda x: x["score"],
            reverse=True
        )

        print("\n" + "=" * 50)
        print("FINAL RECOMMENDATIONS")
        print("=" * 50)

        for rank, item in enumerate(results, start=1):

            print(
                f"{rank}. {item['name']} | "
                f"Price: Rs.{item['price']} | "
                f"Score: {item['score']:.2f}"
            )

        best = results[0]

        print("\n" + "=" * 50)
        print("BEST RECOMMENDATION")
        print("=" * 50)

        print(f"Item      : {best['name']}")
        print(f"Price     : Rs.{best['price']}")
        print(f"Score     : {best['score']:.2f}")

        print("\nReason:")
        print("- Within Budget")
        print("- Highest Weighted Score")
        print("- Best match for user preferences")

        print("\nAI Concepts Used:")
        print("1. Problem Formulation")
        print("2. Knowledge Representation")
        print("3. Constraint Satisfaction Problem (CSP)")
        print("4. Heuristic Evaluation")
        print("5. Greedy Search")
        print("6. Decision Support System")


system = MCDSS()
system.recommend()
